redis:
  host: "127.0.0.1"
  port: 6379
  db: 2
  keyPrefix: "<%= projectNameShort %>:"
  showFriendlyErrorStack: true
mysql:
  host: "localhost"
  user: "root"
  password: "123456"
  database: "<%= projectNameShort %>_test"
