tablePrefix: "<%= projectNameShort %>_"
cookieMaxAge: 604800000 # 默认 cookies 时间 (7day)
sessionSecret: "<%= sessionSecret %>" # session 密钥
sessionPrefix: "sess:" # session 前缀
saltRounds: 10 # 密码加盐长度
loggerDebug: true
redisKey: "<%= projectNameShort %>"
message:
  success: "操作成功"
  error: "操作失败"
